SELECT
  TP.ID_CLIENTE,
  MAX(TC.NM_CLIENTE) AS NM_CLIENTE,
  COUNT(*)           AS qt_pedidos
FROM
  PUBLIC.TBL_PEDIDO AS TP
  INNER JOIN PUBLIC.TBL_CLIENTE AS TC ON TP.ID_CLIENTE=TC.ID_CLIENTE
GROUP BY
  TP.ID_CLIENTE
ORDER BY
  qt_pedidos DESC