SELECT
  TP.nm_categoria,
  TP.DS_PRODUTO,
  TPE.QT_PRODUTO,
  TP.VL_PRODUTO,
  TPE.QT_PRODUTO*TP.VL_PRODUTO AS vl_total,
  TF.DS_RAZAO_SOCIAL,
  TE.ID_ESTOQUE,
  CONCAT(
    TE2.DS_LOGRADOURO,
    ', ',
    TE2.NR_LOGRADOURO,
    ', ',
    TE2.NM_BAIRRO,
    ', ',
    TE2.NM_CIDADE,
    ', ',
    TE2.NM_ESTADO,
    ', ',
    TE2.NM_PAIS
  ) AS ds_endereco_estoque
FROM
  PUBLIC.TBL_PRODUTO AS TP
  INNER JOIN PUBLIC.TBL_FORNECEDOR AS TF ON TP.ID_FORNECEDOR=TF.ID_FORNECEDOR
  INNER JOIN PUBLIC.TBL_PRODUTO_ESTOQUE AS TPE ON TP.ID_PRODUTO=TPE.ID_PRODUTO
  INNER JOIN PUBLIC.TBL_ESTOQUE AS TE ON TPE.ID_ESTOQUE=TE.ID_ESTOQUE
  INNER JOIN PUBLIC.TBL_ENDERECO AS TE2 ON TE.ID_ENDERECO=TE2.ID_ENDERECO